# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

[character]
format="$symbol "
success_symbol = '[](bold green)'
error_symbol = '[](bold red)'

## --- System Info --------------------
[username]
style_user = 'white bold'
style_root = 'black bold'
format = '[$user]($style) '
disabled = false
show_always = true

[directory]
format = 'at [$path]($style)[$read_only]($read_only_style) '
style = "normal italic cyan"
home_symbol = " ~"
read_only = " "
read_only_style = 'bold red'
truncation_symbol = '…/'

[os]
format = '[$symbol](bold white)'
disabled = false

[os.symbols]
Arch = " "
Debian = " "
EndeavourOS = " "
Kali = " "
Linux = " "
Macos = " "
Raspbian = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "

[hostname]
format = '[$ssh_symbol](bold blue) on [$hostname](bold red) '
ssh_symbol = " "

[memory_usage]
symbol = "󰍛 "

[cmd_duration]
format = 'took [$duration](bold italic yellow) '
style = "bold italic"
min_time = 4

## --- Utilities --------------------
[git_branch]
symbol = " "
format = 'on [$symbol$branch]($style)'
truncation_symbol = '…/'
style = 'bold green'

[git_status]
format = '( [$all_status$ahead_behind]($style) )'
style = 'bold green'
conflicted = '[${count}](red) '
untracked = '[${count}](red) '
ahead = '⇡${count} '
diverged = '⇕⇡${ahead_count}⇣${behind_count} '
behind = '⇣${count} '
stashed = '[${count}](green) '
modified = '[${count}](yellow) '
staged = '[${count}](green) '
renamed = '[»${count}](yellow) '
deleted = '[✘${count}](red) '

[docker_context]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = "󰏗 "

## --- Languages --------------------
[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
symbol = " "

[rust]
symbol = " "

[dart]
symbol = " "

[golang]
symbol = " "

[lua]
symbol = " "
