[pyprland]
plugins = [ "scratchpads", "magnify", "fetch_client_menu", "toggle_special" ]

## ---- Scratchpads --------------------
[scratchpads.term]
command = "$TERMINAL --class kittyTerm"
size = "80% 85%"
animation = "fromTop"
margin = 60
unfocus = "hide"
excludes = "*"
hysteresis = 0.25

[scratchpads.software]
command = "$TERMINAL --class kittyPacseek -e $SOFTWARE_MANAGER"
size = "80% 85%"
animation = "fromTop"
margin = 60
unfocus = "hide"
excludes = "*"
hysteresis = 0.25

[scratchpads.volume]
command = "pavucontrol"
class = "pavucontrol"
size = "35% 45%"
animation = "fromTop"
margin = 60
unfocus = "hide"
excludes = "*"
hysteresis = 0.25
lazy = true

[scratchpads.network]
command = "$NETWORK_MANAGER"
class = "network-manager"
size = "35% 45%"
animation = "fromTop"
margin = 60
unfocus = "hide"
excludes = "*"
hysteresis = 0.25
lazy = true

[scratchpads.bluetooth]
command = "$BLUETOOTH_MANAGER"
class = "bluetooth-manager"
size = "35% 45%"
animation = "fromTop"
margin = 60
unfocus = "hide"
excludes = "*"
hysteresis = 0.25
lazy = true

## ---- Fetch Client Menu --------------------
[fetch_client_menu]
engine = "wofi"
