[pyprland]
plugins = [ "scratchpads", "magnify", "fetch_client_menu", "toggle_special" ]

## ---- Scratchpads --------------------
[scratchpads.term]
command = "kitty --class scratchpad"
animation = "fromTop"
margin = 60
excludes = "*"

[scratchpads.volume]
command = "pavucontrol"
animation = "fromTop"
margin = 60
unfocus = "hide"
excludes = "*"
hysteresis = 0.25

## ---- Fetch Client Menu --------------------
[fetch_client_menu]
engine = "wofi"
