# Shell variables
# Generated by 'wal'
wallpaper="/home/test/Downloads/dotfiles/dotfiles/wallpapers/default.jpg"

# Special
background='#101212'
backgroundAlt='#101212'
backgroundAlt2='#101212'

foreground='#c6c7c4'
foregroundAlt='#c6c7c4'
foregroundAlt2='#c6c7c4'

cursor='#c6c7c4'

# Colors
color0='#101212'
color1='#4B5451'
color2='#5B6562'
color3='#6C746F'
color4='#7B817A'
color5='#86867A'
color6='#7A8584'
color7='#c6c7c4'
color8='#8a8b89'
color9='#4B5451'
color10='#5B6562'
color11='#6C746F'
color12='#7B817A'
color13='#86867A'
color14='#7A8584'
color15='#c6c7c4'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
