# Shell variables
# Generated by 'wal'
wallpaper='/home/test/dotfiles/wallpapers/wallpaper5.jpg'

# Special
background='#0C0F12'
foreground='#b2babf'
cursor='#b2babf'

# Colors
color0='#0C0F12'
color1='#35484F'
color2='#3C5463'
color3='#485056'
color4='#5A676E'
color5='#6C7B84'
color6='#827B80'
color7='#b2babf'
color8='#7c8285'
color9='#35484F'
color10='#3C5463'
color11='#485056'
color12='#5A676E'
color13='#6C7B84'
color14='#827B80'
color15='#b2babf'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
