# Shell variables
# Generated by 'wal'
wallpaper='/home/test/dotfiles/wallpapers/default.jpg'

# Special
background='#0f1318'
foreground='#e4e4e1'
cursor='#e4e4e1'

# Colors
color0='#0f1318'
color1='#96744B'
color2='#669949'
color3='#A49368'
color4='#A8C059'
color5='#787C84'
color6='#ADAC9F'
color7='#e4e4e1'
color8='#9f9f9d'
color9='#96744B'
color10='#669949'
color11='#A49368'
color12='#A8C059'
color13='#787C84'
color14='#ADAC9F'
color15='#e4e4e1'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
