# Shell variables
# Generated by 'wal'
wallpaper='/home/test/dotfiles/wallpapers/wallpaper15.jpg'

# Special
background='#0a0c0f'
foreground='#d8dadd'
cursor='#d8dadd'

# Colors
color0='#0a0c0f'
color1='#7C8389'
color2='#90959B'
color3='#AFB3B8'
color4='#B9BDC3'
color5='#BDC0C2'
color6='#BDC2C7'
color7='#d8dadd'
color8='#97989a'
color9='#7C8389'
color10='#90959B'
color11='#AFB3B8'
color12='#B9BDC3'
color13='#BDC0C2'
color14='#BDC2C7'
color15='#d8dadd'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
