#!/bin/bash

echo -e "${BLUE}"
figlet "General"
echo -e "${NOCOLOR}"

packagesPacman=(
    "pacman-contrib"
    "kitty"
    "vim"
    "bluez"
    "bluez-utils"
    "blueman"
    "neovim"
    "wget"
    "unzip"
    "rofi" 
    "chromium"
    "firefox"
    "dunst"
    "starship"
    "mpv" 
    "freerdp" 
    "thunar" 
    "mousepad"
    "noto-fonts" 
    "otf-font-awesome" 
    "ttf-fira-sans" 
    "ttf-fira-code" 
    "ttf-firacode-nerd" 
    "ttf-hack-nerd"
    "ttf-nerd-fonts-symbols"
    "figlet" 
    "vlc" 
    "eza" 
    "python-pip" 
    "python-psutil" 
    "python-rich" 
    "python-click" 
    "pavucontrol" 
    "tumbler" 
    "papirus-icon-theme"
    "breeze-icons"
    "polkit-gnome"
    "brightnessctl"
    "gum"
    "man-pages"
    "nm-connection-editor"
    "gvfs"
    "xdg-user-dirs"
    "networkmanager"
    "network-manager-applet"
    "xarchiver"
    "thunar-archive-plugin"
    "zip"
    "fuse2"
    "gtk4"
    "libadwaita"
    "python-pywal"
    "xdg-desktop-portal"
    "imagemagick"
    "guvcview"
    "neofetch"
    "bat"
    "locate"
);

packagesYay=(
    "bibata-cursor-theme" 
    "trizen"
    "pacseek"
    "zsh-syntax-highlighting"
    "zsh-autosuggestions"
    "zsh-sudo-git"
);

