#!/usr/bin/env bash

echo -e "${BLUE}"
figlet "General"
echo -e "${NOCOLOR}"

export packagesPacman=(
    "kitty"
    "xdg-user-dirs"
    "xdg-desktop-portal"
    "networkmanager"
    "network-manager-applet"
    "nm-connection-editor"
    "net-tools"
    "pavucontrol"
    "wget"
    "zip"
    "unzip"
    "eza"
    "ripgrep"
    "sed"
    "dunst"
    "rofi"
    "starship"
    "mpv"
    "vlc"
    "pastel"
    "bat"
    "jq"
    "fzf"
    "mousepad"
    "brightnessctl"
    "fastfetch"
    "mdcat"
    "ffmpegthumbnailer"
    "unarchiver"
    "poppler"
    "fd"
    "zoxide"
    "btop"
    "cpio"
    "man-pages"
    "man-db"
    "vim"
    "neovim"
    "thunar"
    "thunar-volman"
    "thunar-archive-plugin"
    "bluez"
    "bluez-utils"
    "blueman"
    "chromium"
    "firefox"
    "tumbler"
    "gvfs"
    "xarchiver"
    "fuse2"
    "imagemagick"
    "gtk4"
    "locate"
    "otf-font-awesome"
    "ttf-hack-nerd"
    "ttf-nerd-fonts-symbols"
    "ttf-jetbrains-mono"
    "ttf-firacode-nerd"
    "noto-fonts"
    "noto-fonts-emoji"
    "arc-gtk-theme"
    "papirus-icon-theme"
    "libadwaita"
    "python-pywal"
    "python-pip"
    "python-psutil"
    "python-rich"
    "python-click"
)

export packagesYay=(
    "zsh"
    "fuzzel"
    "bemoji"
    "pacseek"
    "yazi-git"
    "tldr++"
    "nwg-look-bin"
    "python-pywalfox"
    "bibata-cursor-theme"
    "qgnomeplatform-qt5"
    "qgnomeplatform-qt6"
)


## Pacman packages
#"pacman-contrib"
#"freerdp"
#"lazygit"
#"guvcview"
#"polkit-gnome"
#"cmatrix"
#"ttf-nerd-fonts-symbols-mono"
#"ttf-iosevka-nerd"
#"ttf-fira-sans"
#"ttf-fira-code"

## Yay packages
#"trizen"
#"hollywood"
